# Cloudflare Worker configuration for CodegenApp webhook handler

name = "webhook-gateway"
main = "webhook-handler.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[env.production]
name = "webhook-gateway"

[env.development]
name = "webhook-gateway-dev"

# Variables that can be set publicly
[vars]
WORKER_VERSION = "1.0.0"
ENVIRONMENT = "production"

# Secrets (set via: wrangler secret put SECRET_NAME)
# CODEGENAPP_API_URL - URL of the main CodegenApp API (e.g., https://your-domain.com)
# WEBHOOK_SECRET - Secret for validating GitHub webhooks
# API_TOKEN - Token for authenticating with CodegenApp API

# Routes (configure these in Cloudflare dashboard)
# Example: webhook-gateway.your-domain.workers.dev/*

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "WEBHOOK_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects (if needed for state management)
# [[durable_objects.bindings]]
# name = "WEBHOOK_STATE"
# class_name = "WebhookState"

# Worker limits
[limits]
cpu_ms = 10000  # 10 seconds max CPU time

