# Cloudflare Worker Configuration for GitHub Webhook Gateway
# Deploy with: wrangler publish

name = "webhook-gateway"
main = "webhook-gateway.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Worker settings
[env.production]
name = "webhook-gateway"
route = "webhook-gateway.pixeliumperfecto.workers.dev/*"

# Environment variables (set these in Cloudflare Workers dashboard)
[env.production.vars]
# GITHUB_WEBHOOK_SECRET = "your_webhook_secret_here"
# BACKEND_URL = "https://your-backend-url.com"
# API_KEY = "your_api_key_here"

# Development environment
[env.development]
name = "webhook-gateway-dev"

[env.development.vars]
# GITHUB_WEBHOOK_SECRET = "dev_webhook_secret"
# BACKEND_URL = "http://localhost:3001"
# API_KEY = "dev_api_key"

# Triggers
[[triggers]]
crons = ["0 */6 * * *"]  # Health check every 6 hours

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "WEBHOOK_CACHE"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"

# Durable Objects (if needed for state management)
# [[durable_objects.bindings]]
# name = "WEBHOOK_STATE"
# class_name = "WebhookState"

# R2 buckets (if needed for file storage)
# [[r2_buckets]]
# binding = "WEBHOOK_LOGS"
# bucket_name = "webhook-logs-bucket"

# Analytics Engine (if needed for metrics)
# [[analytics_engine_datasets]]
# binding = "WEBHOOK_ANALYTICS"

