name = "webhook-gateway"
main = "webhook-gateway.js"
compatibility_date = "2024-01-01"

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

# Secrets (set via wrangler secret put command):
# GITHUB_WEBHOOK_SECRET
# GRAINCHAIN_API_URL
# BACKEND_API_URL

